# **numpy**

NumPy (Numerical Python) is the core library for scientific computing in Python. This notebook serves as a quick reference guide.

## 1. Initialization
First, we need to import the library. The universal standard is to import it as `np`.

**Action:** Create a code cell below and run:
`import numpy as np`

## 2. Creating Arrays
The `ndarray` is NumPy's main data structure. It's much faster and more memory-efficient than standard Python lists.

**Common Creation Methods:**
* **From a list:** `np.array([1, 2, 3])`
* **Matrix of Zeros:** `np.zeros((3, 3))` *(3x3 grid of 0s)*
* **Matrix of Ones:** `np.ones((2, 4))` *(2x4 grid of 1s)*
* **Number Sequence:** `np.arange(0, 10, 2)` *(Counts 0 to 8, stepping by 2)*
* **Random Numbers:** `np.random.rand(3, 3)` *(3x3 grid of random numbers between 0 and 1)*

## 3. Inspecting Your Data
When working with data, you frequently need to check its shape and type. If you have an array named `arr`, you can use these attributes:

* `arr.shape` ➔ Returns a tuple of the array's dimensions (e.g., `(3, 3)`).
* `arr.size` ➔ Returns the total number of elements.
* `arr.dtype` ➔ Returns the data type (e.g., `int64`, `float64`).

## 4. Indexing & Slicing
Grabbing specific data points from your arrays.

* **Single Element:** `arr[0, 1]` *(Row index 0, Column index 1)*
* **Entire Row:** `arr[0, :]` *(All columns in the first row)*
* **Entire Column:** `arr[:, 1]` *(All rows in the second column)*

## 5. Vectorized Math Operations
NumPy allows you to perform operations on entire arrays at once without writing `for` loops.

**Basic Arithmetic (Element-wise):**
* Addition: `arr + 10`
* Multiplication: `arr * 2`

**Statistical Methods:**
* Maximum value: `np.max(arr)`
* Minimum value: `np.min(arr)`
* Average/Mean: `np.mean(arr)`
* Total Sum: `np.sum(arr)`

In [4]:
import numpy as np

arr = np.array([10,12,5,4])
print(arr)
print(type(arr))

[10 12  5  4]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

touple = ("apple", "banana", "cherry", "date")
arr = np.array(touple)
print(arr)
print(type(arr))

['apple' 'banana' 'cherry' 'date']
<class 'numpy.ndarray'>


In [12]:
import numpy as py

arr_1 = ([20,24,16,8])
arr_2 = ([5,8,2,4])

a = np.array(arr_1)
b = np.array(arr_2)

print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"a % b = {a % b}")
print(f"a / b = {a / b}")

a + b = [25 32 18 12]
a - b = [15 16 14  4]
a * b = [100 192  32  32]
a % b = [0 0 0 0]
a / b = [4. 3. 8. 2.]


# 🧮 **NumPy Mathematical Operators**

NumPy provides built-in functions that correspond to standard Python mathematical operators. Using these functions directly can sometimes offer more advanced parameters, but standard operators work seamlessly on arrays for element-wise calculations.

| Operator | Action | NumPy Function Equivalent |
| :---: | :--- | :--- |
| `+` | Addition | `np.add()` |
| `-` | Subtraction | `np.subtract()` |
| `*` | Multiplication | `np.multiply()` |
| `/` | Division | `np.divide()` |
| `%` | Modulo (Remainder) | `np.remainder()` or `np.mod()` |

In [17]:
import numpy as py

arr = np.array([16,9,25,64])

print(np.sum(arr))
print(np.sqrt(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))

114
[4. 3. 5. 8.]
28.5
9
64


- This line of code creates a 1-dimensional NumPy array containing five integers and forces them to be stored as 32-bit signed integers.

**Key Difference: Memory Usage**
- While both arrays look identical when printed, they differ under the hood:
    - int32 uses 4 bytes of memory per number. It can store integers from -2,147,483,648 to 2,147,483,647.
    - int64 uses 8 bytes of memory per number (double the size). It can store much larger integers, up to roughly 9 quintillion.

- To help you optimize your code further, I can explain:
    - How these memory differences affect computation speed
    - How to safely convert between these types later
    - Which type NumPy picks by default on your operating system

In [20]:
arr_1 = np.array([1,2,3,4,5], dtype=np.int32)
print(arr_1)
print(arr_1.dtype)

arr_2 = np.array([1,2,3,4,5], dtype=np.int64)
print(arr_2)
print(arr_2.dtype)

[1 2 3 4 5]
int32
[1 2 3 4 5]
int64


# 🔢 **NumPy Floating-Point Types: Precision vs. Memory**

The main difference between `float32`, `float64`, and other floating-point types lies in their **precision** (how exact the numbers are) and the **memory** they require. 


### 1. `np.float32` (Single Precision)
* **Memory:** Uses 4 bytes (32 bits) per number.
* **Precision:** Offers about 6 to 7 decimal digits of precision.
* **Pros/Cons:** Uses half the memory of `float64` and is usually faster for computations. However, it is more susceptible to rounding errors.
* **Best for:** Deep learning, standard machine learning, and GPU operations where slight precision loss is acceptable.

### 2. `np.float64` (Double Precision)
* **Memory:** Uses 8 bytes (64 bits) per number.
* **Precision:** Offers about 15 to 16 decimal digits of precision.
* **Pros/Cons:** Highly accurate with minimal rounding errors. However, it consumes twice as much RAM and can slow down performance.
* **Best for:** Scientific computing, financial simulations, and high-precision physics engines. *(Note: This is the default float type in NumPy).*

### 3. `np.float16` (Half Precision)
* **Memory:** Uses 2 bytes (16 bits) per number.
* **Precision:** Very low, offering only about 3 to 4 decimal digits.
* **Best for:** Extreme memory-constrained environments, certain neural network layers, and fast prototyping where accuracy is secondary.

### 4. `np.float128` (Extended Precision)
* **Memory:** Typically uses 16 bytes (128 bits) per number.
* **Precision:** Extremely high, though often limited by underlying hardware architecture.
* **Best for:** Niche, highly sensitive scientific calculations where standard 64-bit precision isn't sufficient.


In [21]:
arr_1 = np.array([1,2,3,4,5], dtype=np.float32)
print(arr_1)
print(arr_1.dtype)

[1. 2. 3. 4. 5.]
float32
