# 🧊 **Demystifying NumPy Multidimensional Arrays**

At the heart of NumPy is the **`ndarray`** (N-dimensional array). Think of it as a highly structured grid of values (all of the same data type) that allows for blazing-fast mathematical operations.

In NumPy terminology, dimensions are called **axes**. The number of axes is referred to as the array's **rank** (or `.ndim`)

## 1. The Anatomy of Dimensions
* **0-D Array (Scalar):** A single distinct value. (e.g., `42`)
* **1-D Array (Vector):** A standard list of values. It has 1 axis (Axis 0).
* **2-D Array (Matrix):** A grid with rows and columns. It has 2 axes (Axis 0 = rows, Axis 1 = columns).
* **3-D Array (Tensor):** A cube of values, like a stack of matrices. It has 3 axes (Axis 0 = depth/layers, Axis 1 = rows, Axis 2 = columns)


### 1. `arr.ndim` (Number of Dimensions)
* **What it tells you:** How many axes (dimensions) the array has. 
* **Output type:** An integer.
* **Think of it as:** Is this a line (1), a flat grid (2), or a cube (3)?

### 2. `arr.shape` (The Structure)
* **What it tells you:** The exact size of the array along *each* of its dimensions.
* **Output type:** A tuple of integers.
* **Think of it as:** The measuring tape. For a 2D matrix, it reads as `(rows, columns)`. For a 3D tensor, it reads as `(depth, rows, columns)`.

### 3. `arr.size` (Total Elements)
* **What it tells you:** The total number of individual data points inside the entire array.
* **Output type:** An integer.
* **Think of it as:** The product of the `shape` tuple. If shape is `(3, 4)`, the size is `12`.

In [ ]:
import numpy as np

sample_2d_array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(sample_2d_array)

print(f"Shape: {sample_2d_array.shape}")

print(f"Size: {sample_2d_array.size}")

print(f"Number of dimensions(ndim): {sample_2d_array.ndim}")

print(f"Data type: {sample_2d_array.dtype}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Number of dimensions(ndim): 2
Data type: int64


In [ ]:
# 3D Arrays

import numpy as np

arr = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],

    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]
    ]
])

print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr)

# Positive indexing 
print(arr[0,2,3])
print(arr[0][2][3]) #Do not use this but this is slow

# Negative Indexing
print(arr[-2,-1,-1])

(2, 3, 4)
24
3
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
12
12
12


In [18]:
import numpy as np

arr = np.array([10,20,30,14])
condition = arr > 15
print(condition)
print(type(condition))

[False  True  True False]
<class 'numpy.ndarray'>
